### ISSUE TITLE
Could not write to log file.

### ISSUE THREAD

**Issue by bleuge** [SabreTools/SabreTools#3] opened 2017-12-25 13:33 UTC
I've run last SabreTools, 9.8.1, with a big input folder (a selection of roms from diverse systems)

i used -dfd -sd -ab

It works, but sometimes writes something like this to the screen:

 >   en System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
>    en System.IO.FileStream.FlushInternalBuffer()
>    en System.IO.FileStream.Flush(Boolean flushToDisk)
>    en System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
>    en System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
>    en SabreTools.Library.Tools.Logger.Log(String output, LogLevel loglevel, Boolean appendPrefix) en C:\Users\Matt\GitHub\SabreTools\SabreTools.Library\Tools\Logger.cs:línea 193
> File added: superpac.3l
> 
> Could not write to log file!
> System.IO.IOException: FileStream no esperaba la posición del controlador de SO. No utilice al mismo tiempo un controlador en un FileStream y en código Win32 u otro FileStream. Esto puede provocar una pérdida de datos.
>    en System.IO.FileStream.VerifyOSHandlePosition()
>    en System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
>    en System.IO.FileStream.FlushInternalBuffer()
>    en System.IO.FileStream.Flush(Boolean flushToDisk)
>    en System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
>    en System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
>    en SabreTools.Library.Tools.Logger.Log(String output, LogLevel loglevel, Boolean appendPrefix) en C:\Users\Matt\GitHub\SabreTools\SabreTools.Library\Tools\Logger.cs:línea 193
> Could not write to log file!
> File added: a26_01.31

**Comment by mnadareski** [comment] 2017-12-30 03:48
Google translate to the rescue, for later use:

> System. IO. IOException: FileStream did not expect the position of the OS driver. Do not at the same time use a driver in a FileStream and in Win32 code or other FileStream. This can cause a loss of data.

**Comment by mnadareski** [comment] 2017-12-30 03:58
Please test one of the newest test builds from the link on the main page. If you still run into this issue, pleas update this.

**Comment by mnadareski** [comment] 2018-01-09 21:18
Unless more information comes to light, I have been unable to reproduce this in recent Git builds. I am closing this for now.

**Closed by mnadareski** 2018-01-09 21:18 UTC
Labels: bug
