### ISSUE TITLE
Error in searching for games in description field

### ISSUE THREAD

**Issue by bleuge** [SabreTools/SabreTools#13] opened 2019-05-22 07:33 UTC
Hi, wish my issues don't bother you :D 

I am using this for filtering some games in a MAME set by game name (description)

>sabretools -ud arcade_v0.209.xml -df -ofg -gd="arkanoid" -f="arkanoid" --script

I did a bat file with many lines like that, looking for some games (a small collection of games for online multiplaying), some games are found and generate a dat for all matches, example: 
These work:

```
D:\emus\vsmame\dd>sabretools -ud arcade_v0.209.xml -df -ofg -gd="Armored Warriors" -f="Armored Warriors" --script 
Processing 'arcade_v0.209.xml'
Creating fully non-merged sets from the DAT
Organizing roms by Game
A total of 48 items will be written out to 'Armored Warriors'
Opening file for writing: D:\emus\vsmame\dd\Armored Warriors.xml
Total runtime: 00:00:08

D:\emus\vsmame\dd>sabretools -ud arcade_v0.209.xml -df -ofg -gd="art of fighting" -f="art of fighting" --script 
Processing 'arcade_v0.209.xml'
Creating fully non-merged sets from the DAT
Organizing roms by Game
A total of 40 items will be written out to 'art of fighting'
Opening file for writing: D:\emus\vsmame\dd\art of fighting.xml
Total runtime: 00:00:08
```
But some games are not found, examples: Arkanoid, Contra, etc... and they are in the Arcade_209 mame dat: 

```
<machine name="ark1ball" sourcefile="arkanoid.cpp">
	<description>Arkanoid (bootleg with MCU, harder)</description>
<machine name="arkangc2" sourcefile="arkanoid.cpp">
	<description>Arkanoid (Game Corporation bootleg, set 2)</description>

<machine name="contra1" sourcefile="contra.cpp">
	<description>Contra (US / Asia, set 2)</description>
<machine name="contra" sourcefile="contra.cpp">
	<description>Contra (US / Asia, set 1)</description>
```

Sabretools can't find it: 

```
D:\emus\vsmame\dd>sabretools -ud arcade_v0.209.xml -df -ofg -gd="arkanoid" -f="arkanoid" --script 
Processing 'arcade_v0.209.xml'
Creating fully non-merged sets from the DAT
Organizing roms by Game
There were no items to write out!
Total runtime: 00:00:08
```

Games with more complex descriptions are found ok,

```
D:\emus\vsmame\dd>sabretools -ud arcade_v0.209.xml -df -ofg -gd="Magical Drop III" -f="Magical Drop III" --script 
Processing 'arcade_v0.209.xml'
Creating fully non-merged sets from the DAT
Organizing roms by Game
A total of 9 items will be written out to 'Magical Drop III'
Opening file for writing: D:\emus\vsmame\dd\Magical Drop III.xml
Total runtime: 00:00:10
```

Am I doing something wrong? Or maybe is some kind of bug? 

Thanks for support!

---
Edit: this works 

>sabretools -ud arcade_v0.209.xml -df -ofg -gd="(.\* )arkanoid(.\* )" -f="arkanoid" --script 

Why "arkanoid" founds nothing, and "Dungeons & Dragons: Shadow over Mystara" works ok? 

Thanks!

**Comment by bleuge** [comment] 2019-05-22 07:41
Edit: this works 

>sabretools -ud arcade_v0.209.xml -df -ofg -gd="(.*)arkanoid(.*)" -f="arkanoid" --script 

Why "arkanoid" founds nothing, and "Dungeons & Dragons: Shadow over Mystara" works ok? 

Thanks!

**Comment by mnadareski** [comment] 2019-05-22 17:13
So, the things that come to mind immediately are:
- Case sensitivity [Edit: Double checked this one and I already accounted for that]
- Exact vs. searchable names (if it doesn't contain regex strings, it does an exact match)

I'm having a feeling it's the latter. Basically, in the code it says this:

    // If the straw has no special characters at all, treat it as an exact match
    if (regexStraw == Regex.Escape(regexStraw))
        regexStraw = "^" + regexStraw + "$";

which means a string with no regex characters (escapable characters) will have the string literal Regex match created from it. So unless you want to get a game description *exactly* as you are writing it, you need to use Regex in your query, as you showed with the `(.*)arkanoid(.*)` example.

**Comment by bleuge** [comment] 2019-05-23 08:19
This is strange... Let's see
"Gauntlet" founds nothing here: 
```
<description>Gauntlet (2 Players, German, rev 1)</description>
<description>Gauntlet (2 Players, German, rev 4)</description>
<description>Gauntlet (2 Players, Japanese, rev 2)</description>
<description>Gauntlet (2 Players, Japanese, rev 5)</description>
<description>Gauntlet (2 Players, rev 3)</description>
<description>Gauntlet (2 Players, rev 6)</description>
<description>Gauntlet (German, rev 10)</description>
<description>Gauntlet (German, rev 3)</description>
...etc
```
but "Dungeons & Dragons Shadow over Mystara" matches these:
```
<description>Dungeons &amp; Dragons: Shadow over Mystara (Asia 960208)</description>
<description>Dungeons &amp; Dragons: Shadow over Mystara (Asia 960619)</description>
<description>Dungeons &amp; Dragons: Shadow over Mystara (Brazil 960223)</description>
<description>Dungeons &amp; Dragons: Shadow over Mystara (Euro 960208)</description>
<description>Dungeons &amp; Dragons: Shadow over Mystara (Euro 960209)</description>
...etc
```
It seems more complex the second one, I'll check the sources maybe I found something.
Thanks

**Comment by bleuge** [comment] 2019-05-23 10:58
I think I found something, I observed that many non-matching strings, most of them have no spaces, the ones with spaces that do not match are clearly wrong, and in that way are not going to match, because mispellings.

I checked the source, you use

`if (!String.IsNullOrWhiteSpace(strawString) && needleString != null)
`
I never coded C# but coded in Pascal for years, so I looked for IsNullOrWhiteSpace and found this: 

https://stackoverflow.com/questions/6976597/string-isnulloremptystring-vs-string-isnullorwhitespacestring

It seems it returns true if it contains just 1 char with spaces

```
public static bool IsNullOrWhiteSpace(String value) {
    if (value == null) return true;

    for(int i = 0; i < value.Length; i++) {
        if(!Char.IsWhiteSpace(value[i])) return false;
    }

    return true;
}
```
So if you look for just 1 word, then this code is executed

`found |= (needle.Equals(straw));`

I think FindValueInList could be rewritten, I guess I can do it myself, and add fuzzy string comparing using a Damerau distance matcher, so people could match much better (if needed). 

Could I just download Visual Studio community or whatever, install, load this and start debugging? :D

I'll do this for -gd option (and maybe any that matches strings)

If string is null or trimmed is null (maybe it's what you really wanted), return false
If string starts with '~' (for example), try a fuzzy string matching
If string contains regexp chars, do a regexp
If string is plain, do the equivalen in c# of a Pos(substring,string):int that I think is the same as strchr, so don't look for exact ^match$ , but just look for the substring in all the string, so it matches all strings containing that substring. 

Anyway, sorry the rant, these are just some ideas, maybe you want consider some of this. 

Thanks very much, Sabretools is sooooo powerful

**Comment by mnadareski** [comment] 2019-05-23 17:36
Your understanding of the `String.IsNullOrWhiteSpace` is flawed. It means that it will return false at the first instance of a non-whitespace character, not the opposite. It means the string may be `null` or contain ONLY whitespace characters. Mixed-character strings will always return `false` regardless of how much whitespace is in them. That is not the issue and does not cause the code path that you are assuming.

The issue is most likely the `Regex.Escape` statement. Looking further into how that code works, it escapes all spaces as well, which will cause the input and output statements to become mismatched. This has a simple fix of adding a `.Replace("\\ ", " ")` to the end of the escape, which will undo that extra. That is why the "more complex" example you have above works, since it does a regex match on the whole string (not as an absolute string).

**Comment by mnadareski** [comment] 2019-05-23 17:45
As a followup, the fix has been pushed as of https://github.com/SabreTools/SabreTools/commit/1f3420a08f3487c0bdfc1eadeaa09d2b4776fe57 . This fix should take care of the rogue whitespace escaping that was happening, causing it to act as it should according to specification. Now generic Regex matching will only occur if there are Regex reserved characters in the input.

**Comment by bleuge** [comment] 2019-05-23 18:59
Yep!, I missed the ! :D , anyway thanks for the bug fixing!

**Closed** 2019-05-23 18:59 UTC
Labels: bug, question
